version: "3.8"

services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - symfony_db:/var/lib/mysql
            - /db/db-init.sql:/docker-entrypoint-initdb.d/:rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app

    php:
        build:
            context: ./php
        volumes:
            - ../:/var/www/symfony
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
            - symfony_app_log:/var/logs
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
            - symfony_app_log:/var/logs
        ports:
            - 8000:80
        networks:
            - symfony_app

    adminer:
        image: adminer
        restart: always
        ports:
            - 8003:8080
        networks:
            - symfony_app

    dozzle:
        image: amir20/dozzle:latest
        environment:
            - DOZZLE_LEVEL=info
            - DOZZLE_NO_ANALYTICS=true
        ports:
            - 8002:8080
        networks:
            - symfony_app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
            test: [ 'CMD', '/dozzle', 'healthcheck' ]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 1s

    swagger:
        image: swaggerapi/swagger-ui
        environment:
            - API_URL=http://localhost:8000/api/doc.json
        ports:
            - 8001:8080

    logviewer:
        image: pierrecdn/phpipam
        volumes:
            -  symfony_app_log:/var/logs
        ports:
            - 8004:8080
        networks:
            - symfony_app

volumes:
    symfony_app_var:
    symfony_app_log:
    symfony_app_vendor:
    symfony_db:

networks:
    symfony_app:
